import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const translations = {
  en: {
    home: "Home",
    booking: "Booking",
    classes: "Classes",
    schedule: "My Schedule",
    learn: "Learn",
    heroTitle: "Reach New Heights",
    heroSubtitle: "Push Your Limits. Conquer the Peak.",
    welcomeTitle: "Welcome to PeakClimb Gym",
    welcomeText1: "Your ultimate destination for indoor rock climbing and fitness. Join us to experience the thrill of climbing and improve your skills with our expert instructors. Whether you are a beginner looking to get started or an advanced climber looking to push your limits, we have something for everyone.",
    welcomeText2: "Our state-of-the-art facilities and supportive community will help you reach new heights. Come and explore the exciting world of climbing with us!",
    programsTitle: "Our Programs",
    beginnerProgram: "Beginner Program",
    beginnerText: "Get started with our beginner climbing classes and learn the basics in a safe and fun environment. Perfect for those new to climbing.",
    intermediateProgram: "Intermediate Program",
    intermediateText: "Take your climbing skills to the next level with our intermediate courses designed to challenge and inspire you. Suitable for climbers with some experience.",
    advancedProgram: "Advanced Program",
    advancedText: "Master advanced climbing techniques and push your limits with our expert-led advanced classes. Ideal for seasoned climbers.",
    locationTitle: "Our Location",
    locationText: "Visit us at our convenient location. Check out the map below to find us.",
    chooseUsTitle: "Why Choose Us?",
    safety: "Safety First",
    safetyText: "Our top priority is the safety of our climbers. We provide high-quality gear and ensure all safety protocols are followed.",
    instructors: "Expert Instructors",
    instructorsText: "Learn from the best in the industry. Our instructors are experienced and passionate about climbing.",
    facilities: "State-of-the-Art Facilities",
    facilitiesText: "Enjoy climbing in our state-of-the-art facilities equipped with the latest climbing walls and equipment.",
    // Booking page translations
    bookingTitle: "Book a Climbing Session or Class",
    dateLabel: "Date:",
    timeLabel: "Time:",
    skillLabel: "Skill Level:",
    selectSkillLevel: "Select Skill Level",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    instructorLabel: "Instructor:",
    selectInstructor: "Select Instructor",
    fullNameLabel: "Full Name:",
    emailLabel: "Email Address:",
    phoneLabel: "Phone Number:",
    bookNowButton: "Book Now",
    groupBookingTitle: "Group Booking",
    participantLabel: "Participant",
    removeButton: "Remove",
    addParticipantButton: "Add Another Participant",
    fullNamePlaceholder: "Full Name",
    emailPlaceholder: "Email Address",
    phonePlaceholder: "Phone Number",
    groupSessionInstructions: "You can add participants to create a group session.",
    // Explore page translations
    filterBy: "Filter by:",
    beginnerLabel: "Beginner",
    intermediateLabel: "Intermediate",
    advancedLabel: "Advanced",
    morningLabel: "Morning",
    afternoonLabel: "Afternoon",
    eveningLabel: "Evening",
    weekdaysLabel: "Weekdays:",
    mondayLabel: "Monday",
    tuesdayLabel: "Tuesday",
    wednesdayLabel: "Wednesday",
    thursdayLabel: "Thursday",
    fridayLabel: "Friday",
    clearFiltersButton: "Clear Filters",
    availableClassesTitle: "Available Classes and Events",
    noClassesMessage: "No classes or events match your filters.",
    selectConfirmButton: "Select & Confirm",
    addedToScheduleMessage: "added to your schedule on",
    // Info page translations
    infoHeroTitle: "Discover the Thrill of Climbing",
    infoHeroSubtitle: "Join us and experience an adventure like no other!",
    howItWorksTitle: "How Our Climbing System Works",
    howItWorksText: "At PeakClimb Gym, we offer a range of climbing experiences tailored to different skill levels. Our climbing walls are equipped with various routes that challenge climbers from beginners to advanced levels. Here’s a quick overview of how you can start climbing with us:",
    step1Title: "Step 1: Orientation",
    step1Text: "All new climbers must complete an orientation session. During this session, you'll learn about our facility, safety guidelines, and basic climbing techniques.",
    step2Title: "Step 2: Gear Up",
    step2Text: "We provide all the necessary climbing gear including harnesses, shoes, and helmets. Make sure your gear is properly fitted and secure before you start climbing.",
    step3Title: "Step 3: Choose Your Route",
    step3Text: "Our walls are color-coded to indicate the difficulty of each route. Start with easier routes and gradually progress to more challenging ones as you build your skills.",
    step4Title: "Step 4: Climb Safely",
    step4Text: "Always climb with a partner and use proper belaying techniques. Follow the safety instructions provided during your orientation and from our staff.",
    step5Title: "Step 5: Take Classes",
    step5Text: "Join our climbing classes to learn new techniques and improve your skills. We offer classes for all levels, from beginners to advanced climbers.",
    climbingLevelsTitle: "Climbing Levels",
    beginnerLevelTitle: "Beginner",
    beginnerLevelText: "Perfect for those who are new to climbing. Learn the basics of climbing techniques, safety, and equipment use.",
    intermediateLevelTitle: "Intermediate",
    intermediateLevelText: "For climbers with some experience. Improve your climbing skills and take on more challenging routes.",
    advancedLevelTitle: "Advanced",
    advancedLevelText: "Designed for seasoned climbers. Master advanced techniques and push your limits on our most challenging routes.",
    safetyTipsTitle: "Safety Tips",
    checkGearTitle: "Check Your Gear",
    checkGearText: "Always inspect your climbing gear before each climb. Look for any signs of wear and tear, and replace any damaged equipment immediately.",
    warmUpTitle: "Warm Up",
    warmUpText: "Perform a proper warm-up routine to prepare your muscles and joints for climbing. Stretching and light exercises can help prevent injuries.",
    followRulesTitle: "Follow the Rules",
    followRulesText: "Adhere to all gym rules and regulations. They are in place to ensure your safety and the safety of others. Listen to the instructions of our staff at all times.",
    stayHydratedTitle: "Stay Hydrated",
    stayHydratedText: "Climbing can be physically demanding. Make sure to drink plenty of water before, during, and after your climbing session to stay hydrated.",
    knowLimitsTitle: "Know Your Limits",
    knowLimitsText: "Don’t push yourself beyond your physical limits. If you feel tired or unwell, take a break. It’s important to climb safely and responsibly.",
    // Schedule page translations
    viewScheduleTitle: "View Your Schedule",
    addSessionButton: "+ Add",
    sessionLabel: "Level: {skill}, Instructor: {instructor}, Participants: {participants}",
    errorMessage1: "You cannot reschedule a public class",
  },
  fr: {
    home: "Accueil",
    booking: "Réservation",
    classes: "Cours",
    schedule: "Mon emploi du temps",
    learn: "Apprendre",
    heroTitle: "Atteignez de nouveaux sommets",
    heroSubtitle: "Repoussez vos limites. Conquérez le sommet.",
    welcomeTitle: "Bienvenue à PeakClimb Gym",
    welcomeText1: "Votre destination ultime pour l'escalade intérieure et le fitness. Rejoignez-nous pour vivre l'excitation de l'escalade et améliorer vos compétences avec nos instructeurs experts. Que vous soyez débutant cherchant à commencer ou grimpeur avancé cherchant à repousser vos limites, nous avons quelque chose pour tout le monde.",
    welcomeText2: "Nos installations de pointe et notre communauté de soutien vous aideront à atteindre de nouveaux sommets. Venez explorer le monde passionnant de l'escalade avec nous !",
    programsTitle: "Nos Programmes",
    beginnerProgram: "Programme Débutant",
    beginnerText: "Commencez avec nos cours d'escalade pour débutants et apprenez les bases dans un environnement sûr et amusant. Parfait pour ceux qui sont nouveaux dans l'escalade.",
    intermediateProgram: "Programme Intermédiaire",
    intermediateText: "Améliorez vos compétences en escalade avec nos cours intermédiaires conçus pour vous défier et vous inspirer. Convient aux grimpeurs ayant un peu d'expérience.",
    advancedProgram: "Programme Avancé",
    advancedText: "Maîtrisez les techniques d'escalade avancées et repoussez vos limites avec nos cours avancés dirigés par des experts. Idéal pour les grimpeurs expérimentés.",
    locationTitle: "Notre Emplacement",
    locationText: "Visitez-nous à notre emplacement pratique. Consultez la carte ci-dessous pour nous trouver.",
    chooseUsTitle: "Pourquoi nous choisir?",
    safety: "La sécurité avant tout",
    safetyText: "Notre priorité absolue est la sécurité de nos grimpeurs. Nous fournissons un équipement de haute qualité et veillons à ce que tous les protocoles de sécurité soient respectés.",
    instructors: "Instructeurs experts",
    instructorsText: "Apprenez des meilleurs de l'industrie. Nos instructeurs sont expérimentés et passionnés par l'escalade.",
    facilities: "Installations de pointe",
    facilitiesText: "Profitez de l'escalade dans nos installations de pointe équipées des derniers murs et équipements d'escalade.",
    // Booking page translations
    bookingTitle: "Réservez une séance ou un cours d'escalade",
    dateLabel: "Date :",
    timeLabel: "Heure :",
    skillLabel: "Niveau de compétence :",
    selectSkillLevel: "Sélectionnez le niveau de compétence",
    beginner: "Débutant",
    intermediate: "Intermédiaire",
    advanced: "Avancé",
    instructorLabel: "Instructeur :",
    selectInstructor: "Sélectionnez l'instructeur",
    fullNameLabel: "Nom complet :",
    emailLabel: "Adresse électronique :",
    phoneLabel: "Numéro de téléphone :",
    bookNowButton: "Réservez maintenant",
    groupBookingTitle: "Réservation de groupe",
    participantLabel: "Participant",
    removeButton: "Supprimer",
    addParticipantButton: "Ajouter un autre participant",
    fullNamePlaceholder: "Nom complet",
    emailPlaceholder: "Adresse électronique",
    phonePlaceholder: "Numéro de téléphone",
    groupSessionInstructions: "Vous pouvez ajouter des participants pour créer une session de groupe.",
    // Explore page translations
    filterBy: "Filtrer par :",
    beginnerLabel: "Débutant",
    intermediateLabel: "Intermédiaire",
    advancedLabel: "Avancé",
    morningLabel: "Matin",
    afternoonLabel: "Après-midi",
    eveningLabel: "Soirée",
    weekdaysLabel: "Jours de la semaine :",
    mondayLabel: "Lundi",
    tuesdayLabel: "Mardi",
    wednesdayLabel: "Mercredi",
    thursdayLabel: "Jeudi",
    fridayLabel: "Vendredi",
    clearFiltersButton: "Réinitialiser",
    availableClassesTitle: "Cours et événements disponibles",
    noClassesMessage: "Aucun cours ou événement ne correspond à vos filtres.",
    selectConfirmButton: "Sélectionner & Confirmer",
    addedToScheduleMessage: "ajouté à votre emploi du temps le",
    // Info page translations
    infoHeroTitle: "Découvrez le frisson de l'escalade",
    infoHeroSubtitle: "Rejoignez-nous et vivez une aventure unique en son genre !",
    howItWorksTitle: "Comment fonctionne notre système d'escalade",
    howItWorksText: "À PeakClimb Gym, nous proposons une gamme d'expériences d'escalade adaptées à différents niveaux de compétence. Nos murs d'escalade sont équipés de diverses voies qui mettent au défi les grimpeurs des niveaux débutants aux niveaux avancés. Voici un aperçu rapide de la façon dont vous pouvez commencer à grimper avec nous :",
    step1Title: "Étape 1 : Orientation",
    step1Text: "Tous les nouveaux grimpeurs doivent suivre une session d'orientation. Au cours de cette session, vous découvrirez nos installations, les consignes de sécurité et les techniques de base de l'escalade.",
    step2Title: "Étape 2 : Équipez-vous",
    step2Text: "Nous fournissons tout le matériel d'escalade nécessaire, y compris les harnais, les chaussures et les casques. Assurez-vous que votre équipement est correctement ajusté et sécurisé avant de commencer à grimper.",
    step3Title: "Choisissez votre voie",
    step3Text: "Nos murs sont codés par couleur pour indiquer la difficulté de chaque voie. Commencez par les voies les plus faciles et progressez graduellement vers des voies plus difficiles à mesure que vous développez vos compétences.",
    step4Title: "Grimpez en toute sécurité",
    step4Text: "Grimpez toujours avec un partenaire et utilisez des techniques d'assurage appropriées. Suivez les consignes de sécurité fournies lors de votre orientation et par notre personnel.",
    step5Title: "Suivez des cours",
    step5Text: "Rejoignez nos cours d'escalade pour apprendre de nouvelles techniques et améliorer vos compétences. Nous proposons des cours pour tous les niveaux, des débutants aux grimpeurs avancés.",
    climbingLevelsTitle: "Niveaux d'escalade",
    beginnerLevelTitle: "Débutant",
    beginnerLevelText: "Parfait pour ceux qui débutent dans l'escalade. Apprenez les bases des techniques d'escalade, de la sécurité et de l'utilisation de l'équipement.",
    intermediateLevelTitle: "Intermédiaire",
    intermediateLevelText: "Pour les grimpeurs ayant une certaine expérience. Améliorez vos compétences en escalade et relevez des défis plus difficiles.",
    advancedLevelTitle: "Avancé",
    advancedLevelText: "Conçu pour les grimpeurs chevronnés. Maîtrisez des techniques avancées et repoussez vos limites sur nos voies les plus difficiles.",
    safetyTipsTitle: "Conseils de sécurité",
    checkGearTitle: "Vérifiez votre équipement",
    checkGearText: "Inspectez toujours votre matériel d'escalade avant chaque ascension. Recherchez les signes d'usure et remplacez immédiatement tout équipement endommagé.",
    warmUpTitle: "Échauffez-vous",
    warmUpText: "Effectuez une routine d'échauffement appropriée pour préparer vos muscles et vos articulations à l'escalade. Les étirements et les exercices légers peuvent aider à prévenir les blessures.",
    followRulesTitle: "Suivez les règles",
    followRulesText: "Respectez toutes les règles et réglementations de la salle de sport. Elles sont en place pour assurer votre sécurité et celle des autres. Écoutez les instructions de notre personnel en tout temps.",
    stayHydratedTitle: "Restez hydraté",
    stayHydratedText: "L'escalade peut être physiquement exigeante. Assurez-vous de boire beaucoup d'eau avant, pendant et après votre séance d'escalade pour rester hydraté.",
    knowLimitsTitle: "Connaissez vos limites",
    knowLimitsText: "Ne vous poussez pas au-delà de vos limites physiques. Si vous vous sentez fatigué ou mal, faites une pause. Il est important de grimper en toute sécurité et de manière responsable.",
    // Schedule page translations
    viewScheduleTitle: "Consultez votre emploi du temps",
    addSessionButton: "+ Ajouter",
    sessionLabel: "Niveau : {skill}, Instructeur : {instructor}, Participants : {participants}",
    errorMessage1: "Vous ne pouvez pas reprogrammer un cours public",
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const switchLanguage = (lang) => {
    setLanguage(lang);
  };

  return (
    <LanguageContext.Provider value={{ language, switchLanguage, translations: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
};
